"""initial schema

Revision ID: 5f6ac2cf5329
Revises: 
Create Date: 2026-06-08 22:13:05.386266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f6ac2cf5329'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('role', sa.Enum('farmer', 'investor', 'buyer', 'logistics', name='user_role'), nullable=False),
    sa.Column('language_preference', sa.Enum('english', 'yoruba', 'pidgin', 'hausa', name='language'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('farms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=False),
    sa.Column('crop_type', sa.String(length=80), nullable=False),
    sa.Column('total_plots', sa.Integer(), nullable=False),
    sa.Column('available_plots', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('listed', 'funded', 'growing', 'harvesting', 'completed', name='farm_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('farm_plots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=True),
    sa.Column('share_percentage', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('amount_invested', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('available', 'reserved', 'owned', name='plot_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['investor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('harvests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('yield_kg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('pending', 'ready', 'in_transit', 'stored', 'sold', name='harvest_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('investor_id', sa.Integer(), nullable=False),
    sa.Column('amount_ngn', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('expected_return_ngn', sa.Integer(), nullable=False),
    sa.Column('actual_return_ngn', sa.Integer(), nullable=False),
    sa.Column('payment_reference', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'completed', 'refunded', name='investment_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['investor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cold_storage_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('harvest_id', sa.Integer(), nullable=False),
    sa.Column('facility_name', sa.String(length=160), nullable=False),
    sa.Column('booked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('temperature_celsius', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['harvest_id'], ['harvests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offtake_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('harvest_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('quantity_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_per_kg', sa.Integer(), nullable=False),
    sa.Column('total_value', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'signed', 'paid', name='contract_status'), nullable=False),
    sa.Column('pdf_url', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['harvest_id'], ['harvests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offtake_contracts')
    op.drop_table('cold_storage_bookings')
    op.drop_table('investments')
    op.drop_table('harvests')
    op.drop_table('farm_plots')
    op.drop_table('farms')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
