"""reference tables: cold storage facilities + crop parameters

Revision ID: d1b5f66cdd03
Revises: 5f6ac2cf5329
Create Date: 2026-06-08 22:56:25.030463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1b5f66cdd03'
down_revision: Union[str, None] = '5f6ac2cf5329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cold_storage_facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=False),
    sa.Column('capacity_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('temperature_celsius', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cold_storage_facilities_facility_code'), 'cold_storage_facilities', ['facility_code'], unique=True)
    op.create_index(op.f('ix_cold_storage_facilities_location'), 'cold_storage_facilities', ['location'], unique=False)
    op.create_table('crop_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop_type', sa.String(length=80), nullable=False),
    sa.Column('price_per_kg', sa.Integer(), nullable=False),
    sa.Column('return_multiplier', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('harvest_months', sa.Integer(), nullable=False),
    sa.Column('spacing_cm', sa.Integer(), nullable=False),
    sa.Column('plant_window', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_parameters_crop_type'), 'crop_parameters', ['crop_type'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crop_parameters_crop_type'), table_name='crop_parameters')
    op.drop_table('crop_parameters')
    op.drop_index(op.f('ix_cold_storage_facilities_location'), table_name='cold_storage_facilities')
    op.drop_index(op.f('ix_cold_storage_facilities_facility_code'), table_name='cold_storage_facilities')
    op.drop_table('cold_storage_facilities')
    # ### end Alembic commands ###
