"""sponsorships and milestones

Revision ID: e8a3bd5d874c
Revises: d1b5f66cdd03
Create Date: 2026-10-07 03:41:41.028880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8a3bd5d874c'
down_revision: Union[str, None] = 'd1b5f66cdd03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # New chat role for people who sponsor a farm. Not used in this migration, so it
    # is safe inside the migration transaction (PostgreSQL 12+).
    op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'sponsor'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sponsorships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('sponsor_id', sa.Integer(), nullable=False),
    sa.Column('total_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('pending_approval', 'active', 'completed', 'cancelled', name='sponsorship_status'), nullable=False),
    sa.Column('paypal_order_id', sa.String(length=64), nullable=True),
    sa.Column('paypal_vault_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['sponsor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsorships_farm_id'), 'sponsorships', ['farm_id'], unique=False)
    op.create_index(op.f('ix_sponsorships_paypal_order_id'), 'sponsorships', ['paypal_order_id'], unique=True)
    op.create_index(op.f('ix_sponsorships_reference'), 'sponsorships', ['reference'], unique=True)
    op.create_index(op.f('ix_sponsorships_sponsor_id'), 'sponsorships', ['sponsor_id'], unique=False)
    op.create_table('sponsorship_milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sponsorship_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('evidence_required', sa.Text(), nullable=True),
    sa.Column('share_bps', sa.Integer(), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('locked', 'awaiting_evidence', 'needs_review', 'payment_failed', 'paid', name='milestone_status'), nullable=False),
    sa.Column('evidence_sha256', sa.String(length=64), nullable=True),
    sa.Column('verdict_summary', sa.Text(), nullable=True),
    sa.Column('verdict_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paypal_order_id', sa.String(length=64), nullable=True),
    sa.Column('paypal_capture_id', sa.String(length=64), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=160), nullable=True),
    sa.Column('payment_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sponsorship_id'], ['sponsorships.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sponsorship_id', 'sequence', name='uq_sponsorship_milestone_sequence')
    )
    op.create_index(op.f('ix_sponsorship_milestones_evidence_sha256'), 'sponsorship_milestones', ['evidence_sha256'], unique=False)
    op.create_index(op.f('ix_sponsorship_milestones_sponsorship_id'), 'sponsorship_milestones', ['sponsorship_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sponsorship_milestones_sponsorship_id'), table_name='sponsorship_milestones')
    op.drop_index(op.f('ix_sponsorship_milestones_evidence_sha256'), table_name='sponsorship_milestones')
    op.drop_table('sponsorship_milestones')
    op.drop_index(op.f('ix_sponsorships_sponsor_id'), table_name='sponsorships')
    op.drop_index(op.f('ix_sponsorships_reference'), table_name='sponsorships')
    op.drop_index(op.f('ix_sponsorships_paypal_order_id'), table_name='sponsorships')
    op.drop_index(op.f('ix_sponsorships_farm_id'), table_name='sponsorships')
    op.drop_table('sponsorships')
    # ### end Alembic commands ###
    op.execute("DROP TYPE IF EXISTS milestone_status")
    op.execute("DROP TYPE IF EXISTS sponsorship_status")
    # The 'sponsor' value stays on user_role: PostgreSQL cannot remove an enum value,
    # and leaving it is harmless.
