"""tuago rail payouts and web sponsors

Revision ID: f180724a6109
Revises: e8a3bd5d874c
Create Date: 2026-10-07 04:05:49.132914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f180724a6109'
down_revision: Union[str, None] = 'e8a3bd5d874c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # New tranche state for the naira rail: verified, waiting for the sponsor to pay.
    # Not used in this migration, so it is safe inside the transaction (PostgreSQL 12+).
    op.execute("ALTER TYPE milestone_status ADD VALUE IF NOT EXISTS 'awaiting_payment'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payout_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bank_code', sa.String(length=12), nullable=False),
    sa.Column('bank_name', sa.String(length=120), nullable=True),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('account_name', sa.String(length=160), nullable=False),
    sa.Column('tuago_subaccount_id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payout_accounts_user_id'), 'payout_accounts', ['user_id'], unique=True)
    op.create_table('farmer_disbursements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('source_currency', sa.String(length=3), nullable=False),
    sa.Column('source_minor', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('amount_kobo', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('tuago_session_id', sa.String(length=80), nullable=True),
    sa.Column('tuago_reference', sa.String(length=80), nullable=True),
    sa.Column('pay_bank_name', sa.String(length=120), nullable=True),
    sa.Column('pay_account_number', sa.String(length=20), nullable=True),
    sa.Column('pay_account_name', sa.String(length=160), nullable=True),
    sa.Column('pay_expires_at', sa.String(length=40), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['milestone_id'], ['sponsorship_milestones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmer_disbursements_farmer_id'), 'farmer_disbursements', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_farmer_disbursements_milestone_id'), 'farmer_disbursements', ['milestone_id'], unique=True)
    op.create_index(op.f('ix_farmer_disbursements_tuago_reference'), 'farmer_disbursements', ['tuago_reference'], unique=False)
    op.create_index(op.f('ix_farmer_disbursements_tuago_session_id'), 'farmer_disbursements', ['tuago_session_id'], unique=False)
    op.add_column('sponsorship_milestones', sa.Column('evidence_photo', sa.String(length=200), nullable=True))
    op.add_column('sponsorship_milestones', sa.Column('sponsor_update', sa.Text(), nullable=True))
    op.add_column('sponsorship_milestones', sa.Column('tuago_session_id', sa.String(length=80), nullable=True))
    op.add_column('sponsorship_milestones', sa.Column('payment_reference', sa.String(length=80), nullable=True))
    op.add_column('sponsorship_milestones', sa.Column('payment_url', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_sponsorship_milestones_payment_reference'), 'sponsorship_milestones', ['payment_reference'], unique=False)
    op.create_index(op.f('ix_sponsorship_milestones_tuago_session_id'), 'sponsorship_milestones', ['tuago_session_id'], unique=False)
    op.add_column('sponsorships', sa.Column('rail', sa.String(length=10), server_default='paypal', nullable=False))
    op.add_column('users', sa.Column('email', sa.String(length=160), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    op.drop_column('sponsorships', 'rail')
    op.drop_index(op.f('ix_sponsorship_milestones_tuago_session_id'), table_name='sponsorship_milestones')
    op.drop_index(op.f('ix_sponsorship_milestones_payment_reference'), table_name='sponsorship_milestones')
    op.drop_column('sponsorship_milestones', 'payment_url')
    op.drop_column('sponsorship_milestones', 'payment_reference')
    op.drop_column('sponsorship_milestones', 'tuago_session_id')
    op.drop_column('sponsorship_milestones', 'sponsor_update')
    op.drop_column('sponsorship_milestones', 'evidence_photo')
    op.drop_index(op.f('ix_farmer_disbursements_tuago_session_id'), table_name='farmer_disbursements')
    op.drop_index(op.f('ix_farmer_disbursements_tuago_reference'), table_name='farmer_disbursements')
    op.drop_index(op.f('ix_farmer_disbursements_milestone_id'), table_name='farmer_disbursements')
    op.drop_index(op.f('ix_farmer_disbursements_farmer_id'), table_name='farmer_disbursements')
    op.drop_table('farmer_disbursements')
    op.drop_index(op.f('ix_payout_accounts_user_id'), table_name='payout_accounts')
    op.drop_table('payout_accounts')
    # ### end Alembic commands ###
    # 'awaiting_payment' stays on milestone_status: PostgreSQL cannot remove an enum value.
