"""Offtake contract PDF generation + signing tools."""

from __future__ import annotations

import os
from datetime import date
from typing import Any

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.pdfgen import canvas

from app.agents.base import Tool
from app.tools.telegram import send_text_message
from app.utils.logger import get_logger
from app.utils.money import format_naira

log = get_logger("yieldra.tools.contracts")

# Where generated PDFs land. Served at /static/contracts/<file> by app.main.
CONTRACTS_DIR = os.path.join("generated", "contracts")


def _ensure_dir() -> None:
    os.makedirs(CONTRACTS_DIR, exist_ok=True)


async def generate_contract_pdf(harvest_id: str, buyer_id: str, terms: dict[str, Any]) -> str:
    """Render a draft offtake contract PDF and return its public URL path.

    ``terms`` may contain: crop_type, quantity_kg, price_per_kg (kobo),
    total_value (kobo), farmer_name, buyer_name, location, delivery_date.
    """
    _ensure_dir()
    filename = f"contract_h{harvest_id}_b{buyer_id}.pdf"
    path = os.path.join(CONTRACTS_DIR, filename)

    c = canvas.Canvas(path, pagesize=A4)
    width, height = A4
    y = height - 3 * cm

    def line(text: str, size: int = 11, dy: float = 0.8 * cm, bold: bool = False) -> None:
        nonlocal y
        c.setFont("Helvetica-Bold" if bold else "Helvetica", size)
        c.drawString(2.5 * cm, y, text)
        y -= dy

    line("YIELDRA OFFTAKE CONTRACT", 18, 1.2 * cm, bold=True)
    line(f"Date: {date.today().isoformat()}", 10)
    line(f"Contract Ref: H{harvest_id}-B{buyer_id}", 10, 1.0 * cm)

    line("PARTIES", 13, 0.9 * cm, bold=True)
    line(f"Farmer / Seller: {terms.get('farmer_name', 'N/A')}")
    line(f"Buyer: {terms.get('buyer_name', 'N/A')}")
    line(f"Farm Location: {terms.get('location', 'N/A')}", dy=1.0 * cm)

    line("TERMS", 13, 0.9 * cm, bold=True)
    line(f"Crop: {terms.get('crop_type', 'N/A')}")
    line(f"Quantity: {terms.get('quantity_kg', 0)} kg")
    if terms.get("price_per_kg") is not None:
        line(f"Price per kg: {format_naira(int(terms['price_per_kg']))}")
    if terms.get("total_value") is not None:
        line(f"Total Value: {format_naira(int(terms['total_value']))}", bold=True)
    line(f"Delivery Date: {terms.get('delivery_date', 'TBD')}", dy=1.2 * cm)

    line("SIGNATURES", 13, 0.9 * cm, bold=True)
    line("Farmer: ____________________      Buyer: ____________________", 10)

    c.setFont("Helvetica-Oblique", 8)
    c.drawString(2.5 * cm, 2 * cm, "Generated by Yieldra. Both parties must confirm via Telegram to sign.")
    c.showPage()
    c.save()

    url = f"/static/contracts/{filename}"
    log.info("contract pdf generated %s", path)
    return url


async def send_contract_for_signing(
    contract_id: str, farmer_phone: str, buyer_phone: str, pdf_url: str = ""
) -> dict[str, Any]:
    """Notify both parties to review and confirm a contract via Telegram."""
    msg = (
        f"Yieldra contract {contract_id} is ready. Review and reply YES to confirm, "
        f"or send a counter-offer. {pdf_url}"
    )
    farmer = await send_text_message(farmer_phone, msg)
    buyer = await send_text_message(buyer_phone, msg)
    log.info("contract %s sent for signing", contract_id)
    return {"contract_id": contract_id, "farmer_notified": farmer, "buyer_notified": buyer}


CONTRACT_TOOLS: list[Tool] = [
    Tool(
        name="generate_contract_pdf",
        description="Generate a draft offtake contract PDF for a harvest and buyer.",
        parameters={
            "type": "object",
            "properties": {
                "harvest_id": {"type": "string"},
                "buyer_id": {"type": "string"},
                "terms": {
                    "type": "object",
                    "description": "crop_type, quantity_kg, price_per_kg (kobo), total_value (kobo), names, location, delivery_date",
                },
            },
            "required": ["harvest_id", "buyer_id", "terms"],
        },
        handler=generate_contract_pdf,
    ),
]
